# Generated by Django 3.1.1 on 2020-11-02 20:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=100, verbose_name='Nombre')),
                ('kcal_hundred_gr', models.CharField(max_length=4, verbose_name='Kcal 100 gramos')),
                ('gr_hc', models.CharField(max_length=4, verbose_name='Gramos de Hidratos de Carbono')),
                ('gr_pr', models.CharField(max_length=4, verbose_name='Gramos de Proteínas')),
                ('gr_lip', models.CharField(max_length=4, verbose_name='Gramos de Grasas')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=50, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='Required', verbose_name='Descripcion')),
                ('hc_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Hidratos de Carbono')),
                ('pr_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Proteinas')),
                ('gr_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Lípidos')),
            ],
            options={
                'verbose_name': 'Tipo Dieta',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=20, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='Required', verbose_name='Descripcion')),
                ('aliment', models.ManyToManyField(to='diet.Aliment')),
            ],
            options={
                'verbose_name': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required', max_length=50, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='required', verbose_name='Descripcion Dieta')),
                ('calorias', models.CharField(help_text='required', max_length=30, verbose_name='Calorías de la Dieta')),
                ('aliments', models.ManyToManyField(to='diet.Aliment')),
                ('meals', models.ManyToManyField(to='diet.Meal')),
                ('type_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.diettype', verbose_name='Tipo Dieta')),
            ],
            options={
                'verbose_name': 'Dieta',
            },
        ),
    ]
