# Generated by Django 3.1.1 on 2020-11-09 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(default='alonso@alonso.es', on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
