# Generated by Django 3.1.1 on 2020-11-10 20:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_diet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='required', null=True, verbose_name='Descripcion Dieta'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(blank=True, help_text='required', max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
