# Generated by Django 3.1.3 on 2020-11-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20201110_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='aliments',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='type_diet',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='aliment',
        ),
        migrations.DeleteModel(
            name='Aliment',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='DietType',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
