# Generated by Django 3.1.3 on 2020-11-12 13:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0004_auto_20201112_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=100, verbose_name='Nombre')),
                ('kcal_hundred_gr', models.CharField(max_length=4, verbose_name='Kcal 100 gramos')),
                ('gr_hc', models.CharField(max_length=4, verbose_name='Gramos de Hidratos de Carbono')),
                ('gr_pr', models.CharField(max_length=4, verbose_name='Gramos de Proteínas')),
                ('gr_lip', models.CharField(max_length=4, verbose_name='Gramos de Grasas')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
        migrations.CreateModel(
            name='AlimentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre Comida')),
                ('day', models.CharField(max_length=20, verbose_name='Día')),
                ('comments', ckeditor.fields.RichTextField(verbose_name='Comentarios Adicionales')),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.aliment')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='required', max_length=50, null=True, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='required', null=True, verbose_name='Descripcion Dieta')),
                ('calorias', models.CharField(help_text='required', max_length=30, verbose_name='Calorías de la Dieta')),
                ('aliments', models.ManyToManyField(through='diet.AlimentUser', to='diet.Aliment')),
            ],
            options={
                'verbose_name': 'Dieta',
            },
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=50, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='Required', verbose_name='Descripcion')),
                ('hc_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Hidratos de Carbono')),
                ('pr_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Proteinas')),
                ('gr_percentage', models.CharField(help_text='Required', max_length=3, verbose_name='% Lípidos')),
            ],
            options={
                'verbose_name': 'Tipo Dieta',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=20, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='Required', verbose_name='Descripcion')),
                ('aliment', models.ManyToManyField(to='diet.Aliment')),
            ],
            options={
                'verbose_name': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='MealUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Comida')),
                ('day', models.CharField(max_length=20, verbose_name='Día')),
                ('comments', ckeditor.fields.RichTextField(verbose_name='Comentarios Adicionales')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.diet')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='meals',
            field=models.ManyToManyField(through='diet.MealUser', to='diet.Meal'),
        ),
        migrations.AddField(
            model_name='diet',
            name='type_diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.diettype', verbose_name='Tipo Dieta'),
        ),
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='alimentuser',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.diet'),
        ),
        migrations.AddField(
            model_name='alimentuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
