# Generated by Django 3.1.3 on 2020-11-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_auto_20201113_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mealuser',
            name='name',
        ),
    ]
