# Generated by Django 3.1.3 on 2020-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_auto_20201113_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentuser',
            name='gramos',
            field=models.CharField(default='2', max_length=20, verbose_name='Gramos Alimento'),
            preserve_default=False,
        ),
    ]
