# Generated by Django 3.1.3 on 2020-11-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_alimentuser_gramos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='aliment',
        ),
    ]
