# Generated by Django 3.1.3 on 2020-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_remove_meal_aliment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='gr_gramos',
            field=models.CharField(default='21', max_length=20, verbose_name='Gramos Grasas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='hc_gramos',
            field=models.CharField(default='21', max_length=20, verbose_name='Gramos Hidratos de Carbono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='pr_gramos',
            field=models.CharField(default='21', max_length=20, verbose_name='Gramos Proteínas'),
            preserve_default=False,
        ),
    ]
