# Generated by Django 3.1.3 on 2020-11-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_auto_20201114_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentuser',
            options={'verbose_name': 'Alimentos Usuario'},
        ),
        migrations.AlterModelOptions(
            name='mealuser',
            options={'verbose_name': 'Comidas Usuario'},
        ),
    ]
