# Generated by Django 3.1.3 on 2020-11-25 11:30

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_auto_20201114_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='calorias_gr',
            field=models.CharField(default='11', help_text='required', max_length=30, verbose_name='Calorías GR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='calorias_hc',
            field=models.CharField(default='11', help_text='required', max_length=30, verbose_name='Calorías HC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='calorias_pr',
            field=models.CharField(default='11', help_text='required', max_length=30, verbose_name='Calorías PR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_hc',
            field=models.FloatField(max_length=4, verbose_name='Gramos de Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_lip',
            field=models.FloatField(max_length=4, verbose_name='Gramos de Grasas'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_pr',
            field=models.FloatField(max_length=4, verbose_name='Gramos de Proteínas'),
        ),
        migrations.AlterField(
            model_name='alimentuser',
            name='day',
            field=models.DateField(max_length=20, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion Dieta'),
        ),
        migrations.AlterField(
            model_name='mealuser',
            name='day',
            field=models.DateField(max_length=20, verbose_name='Día'),
        ),
    ]
