# Generated by Django 3.1.3 on 2020-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_auto_20201125_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentuser',
            name='meal_number',
            field=models.IntegerField(default='1', verbose_name='Número de Comida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealuser',
            name='meal_number',
            field=models.IntegerField(default='1', verbose_name='Número de Comida'),
            preserve_default=False,
        ),
    ]
