# Generated by Django 3.1.3 on 2020-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_auto_20201125_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='visible',
            field=models.BooleanField(default='0', verbose_name='¿Visible?'),
            preserve_default=False,
        ),
    ]
