# Generated by Django 3.1.3 on 2020-12-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0014_diet_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='created_by',
            field=models.ForeignKey(default='flalonso17@esei.uvigo.es', on_delete=django.db.models.deletion.CASCADE, related_name='Usuario entrenador+', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario Cliente+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
