# Generated by Django 3.1.3 on 2021-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_auto_20210107_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='gr_hc',
            field=models.CharField(max_length=5, verbose_name='Gramos de Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_lip',
            field=models.CharField(max_length=5, verbose_name='Gramos de Grasas'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_pr',
            field=models.CharField(max_length=5, verbose_name='Gramos de Proteínas'),
        ),
    ]
