# Generated by Django 3.1.3 on 2021-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0017_auto_20210107_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='gr_hc',
            field=models.FloatField(max_length=5, verbose_name='Gramos de Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_lip',
            field=models.FloatField(max_length=5, verbose_name='Gramos de Grasas'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='gr_pr',
            field=models.FloatField(max_length=5, verbose_name='Gramos de Proteínas'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='kcal_hundred_gr',
            field=models.FloatField(max_length=5, verbose_name='Kcal 100 gramos'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='gr_gramos',
            field=models.FloatField(max_length=20, verbose_name='Gramos Grasas'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='hc_gramos',
            field=models.FloatField(max_length=20, verbose_name='Gramos Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='pr_gramos',
            field=models.FloatField(max_length=20, verbose_name='Gramos Proteínas'),
        ),
    ]
