# Generated by Django 3.1.3 on 2021-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0018_auto_20210107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentuser',
            name='gramos',
            field=models.FloatField(max_length=20, verbose_name='Gramos Alimento'),
        ),
    ]
