# Generated by Django 3.1.3 on 2020-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(help_text='Required', verbose_name='Cantidad a pagar'),
        ),
    ]
