# Generated by Django 3.1.3 on 2020-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201125_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.FloatField(help_text='Required', verbose_name='Cantidad a pagar'),
        ),
    ]
