# Generated by Django 3.1.1 on 2020-11-02 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('public', models.BooleanField(verbose_name='¿Visible?')),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='URL Amigable')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
    ]
