# Generated by Django 3.1.3 on 2020-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201214_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.TimeField(auto_now=True, verbose_name='Fecha mensaje'),
        ),
    ]
