# Generated by Django 3.1.3 on 2020-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201214_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha mensaje'),
        ),
    ]
