# Generated by Django 3.1.1 on 2020-11-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
