# Generated by Django 3.1.3 on 2020-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201113_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.ImageField(default='111.png', upload_to='profile-photos', verbose_name='Fotos Subidas'),
            preserve_default=False,
        ),
    ]
