# Generated by Django 3.1.3 on 2020-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201119_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fecha_subida',
            field=models.DateField(auto_now=True, verbose_name='Fecha Subida'),
        ),
        migrations.AddField(
            model_name='image',
            name='peso',
            field=models.IntegerField(default='70', verbose_name='Peso Usuario'),
            preserve_default=False,
        ),
    ]
