# Generated by Django 3.1.3 on 2020-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, choices=[('Hombre', 'Masculino'), ('Mujer', 'Femenino')], help_text='Required', max_length=10, null=True, verbose_name='Género'),
        ),
    ]
