# Generated by Django 3.1.1 on 2020-11-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
