# Generated by Django 3.1.1 on 2020-11-03 22:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201103_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='comments',
            field=ckeditor.fields.RichTextField(default='cosas', verbose_name='Comentarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='number_training',
            field=models.IntegerField(default='1', verbose_name='Número de entrenamiento'),
            preserve_default=False,
        ),
    ]
