# Generated by Django 3.1.1 on 2020-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20201104_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='day',
            field=models.CharField(default='1', max_length=2, verbose_name='Día'),
            preserve_default=False,
        ),
    ]
