# Generated by Django 3.1.3 on 2020-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20201104_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='fecha_fin',
            field=models.DateField(default='2020-11-21', verbose_name='Fecha Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='fecha_inicio',
            field=models.DateField(default='2020-11-22', verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
    ]
