# Generated by Django 3.1.3 on 2020-12-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20201209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(help_text='required', max_length=50, verbose_name='Nombre'),
        ),
    ]
