# Generated by Django 3.1.3 on 2021-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20201226_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='visible',
            field=models.BooleanField(default='1', verbose_name='¿Visible?'),
            preserve_default=False,
        ),
    ]
