# Generated by Django 3.1.3 on 2021-01-02 17:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0014_training_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(default='flalonso17@esei.uvigo.es', on_delete=django.db.models.deletion.CASCADE, related_name='Usuario Entrnador+', to='user.user', verbose_name='Entrenador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Required', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='training',
            name='fecha_fin',
            field=models.DateField(help_text='Required', verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='training',
            name='fecha_inicio',
            field=models.DateField(help_text='Required', verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(help_text='Required', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='training',
            name='visible',
            field=models.BooleanField(help_text='Required', verbose_name='¿Visible?'),
        ),
    ]
